# Generated by Django 3.2.9 on 2021-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('title_little', models.CharField(blank=True, max_length=100)),
                ('subtitle_little', models.CharField(blank=True, max_length=100)),
                ('icon_1', models.CharField(blank=True, default='ti-location-pin', max_length=100)),
                ('title_1', models.CharField(blank=True, max_length=100)),
                ('subtitle_1', models.CharField(blank=True, max_length=100)),
                ('icon_2', models.CharField(blank=True, default='ti-location-pin', max_length=100)),
                ('title_2', models.CharField(blank=True, max_length=100)),
                ('subtitle_2', models.CharField(blank=True, max_length=100)),
                ('icon_3', models.CharField(blank=True, default='ti-location-pin', max_length=100)),
                ('title_3', models.CharField(blank=True, max_length=100)),
                ('subtitle_3', models.CharField(blank=True, max_length=100)),
                ('icon_4', models.CharField(blank=True, default='ti-location-pin', max_length=100)),
                ('title_4', models.CharField(blank=True, max_length=100)),
                ('subtitle_4', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='ti-location-pin', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('sub_subtitle', models.CharField(blank=True, max_length=100)),
                ('is_head_office', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
            },
        ),
    ]
