# Generated by Django 3.2.9 on 2022-02-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_little',
            field=models.TextField(blank=True),
        ),
    ]
