# Generated by Django 3.2.9 on 2022-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_aboutus_subtitle_little'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='icon_1',
            field=models.CharField(blank=True, default='ti-location-pin', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='icon_2',
            field=models.CharField(blank=True, default='ti-location-pin', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='icon_3',
            field=models.CharField(blank=True, default='ti-location-pin', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='icon_4',
            field=models.CharField(blank=True, default='ti-location-pin', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title_little',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
