# Generated by Django 3.2.9 on 2022-02-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20220215_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title_0_en',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_0_ru',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
