# Generated by Django 3.2.9 on 2022-03-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20220301_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusdetailinformation',
            options={'verbose_name': 'About Us Detail Information', 'verbose_name_plural': 'About Us Detail Information'},
        ),
        migrations.AlterModelOptions(
            name='aboutustext',
            options={'verbose_name': 'About Us Text', 'verbose_name_plural': 'About Us Text'},
        ),
    ]
