# Generated by Django 3.2.9 on 2022-03-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20220301_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutustext',
            name='text_0',
            field=models.TextField(blank=True, max_length=12000),
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text_0_en',
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='aboutustext',
            name='text_0_ru',
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
    ]
