# Generated by Django 3.2.9 on 2022-03-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20220301_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_1_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_1_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_2_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_2_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_3_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_3_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_4_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='subtitle_4_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_1_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_1_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_2_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_2_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_3_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_3_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_4_en',
        ),
        migrations.RemoveField(
            model_name='aboutusdetailinformation',
            name='title_4_ru',
        ),
        migrations.RemoveField(
            model_name='aboutustext',
            name='text_0_en',
        ),
        migrations.RemoveField(
            model_name='aboutustext',
            name='text_0_ru',
        ),
    ]
