# Generated by Django 3.2.9 on 2022-03-01 08:18

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220301_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutustext',
            name='text_0',
        ),
        migrations.CreateModel(
            name='AboutUsTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('text_0', models.TextField(blank=True, max_length=12000)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='applications.aboutustext')),
            ],
            options={
                'verbose_name': 'About Us Text Translation',
                'db_table': 'applications_aboutustext_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
