# Generated by Django 3.2.9 on 2022-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20220302_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdetailinformation',
            name='icon_2',
            field=models.CharField(blank=True, default='flaticon-apartments', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutusdetailinformation',
            name='icon_3',
            field=models.CharField(blank=True, default='flaticon-student-housing', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutusdetailinformation',
            name='icon_4',
            field=models.CharField(blank=True, default='flaticon-modern-house-4', max_length=200),
        ),
    ]
