# Generated by Django 3.2.9 on 2021-12-23 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Meta description')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('regular_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.regularurl')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DetailAndFeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Meta description')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('type_of_deal', models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SALE', 'Sale')], max_length=4, verbose_name='Type of deal')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('hidden_details', models.CharField(blank=True, max_length=255, verbose_name='Hidden details')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('popular', models.BooleanField(blank=True, null=True, verbose_name='Popular')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(null=True, upload_to='documents')),
                ('rent_object_view_count', models.IntegerField(default=0)),
                ('address', django_google_maps.fields.AddressField(max_length=200, null=True)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, null=True)),
                ('amenities', models.ManyToManyField(blank=True, to='objects.Amenity')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.category')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currencies.currency')),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('regular_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.regularurl')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentObjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('rent_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentObjectReserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Check In')),
                ('checkout', models.DateField(verbose_name='Check Out')),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('kids', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('rent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='RentObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('rent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='RentObjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents')),
                ('rent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('areas', models.FloatField(default=0, verbose_name='Areas')),
                ('uom', models.CharField(choices=[('ft', 'sq ft'), ('m', 'sq m')], default='ft', max_length=6, verbose_name='Unit of Measures')),
                ('attachment', models.FileField(upload_to='', verbose_name='Attachment')),
                ('rent_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
            ],
        ),
        migrations.CreateModel(
            name='DetailAndFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('rent_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.rentobject')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objects.detailandfeaturetype')),
            ],
            options={
                'verbose_name_plural': 'Details And Features',
            },
        ),
    ]
