# Generated by Django 3.2.9 on 2021-12-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobject',
            name='location',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='street',
        ),
    ]
