# Generated by Django 3.2.9 on 2021-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20211227_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='type_rent_period',
            field=models.CharField(choices=[('NIGHT', 'Per Night'), ('WEEK', 'Per Week'), ('MONTH', 'Per Month')], max_length=6, null=True),
        ),
    ]
