# Generated by Django 3.2.9 on 2021-12-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_rentobject_type_rent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobjectreview',
            name='pre_moderation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='type_rent_period',
            field=models.CharField(choices=[('Per Night', 'Per Night'), ('Per Week', 'Per Week'), ('Per Month', 'Per Month')], default='Per Night', max_length=10, null=True),
        ),
    ]
