# Generated by Django 3.2.9 on 2021-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20211227_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobjectreview',
            name='pre_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
