# Generated by Django 3.2.9 on 2021-12-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_rentobjectreview_pre_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobjectreserv',
            name='animals',
            field=models.BooleanField(default=False),
        ),
    ]
