# Generated by Django 3.2.9 on 2022-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_rentobjectreserv_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
