# Generated by Django 3.2.9 on 2022-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_rentobjectreserv_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='seo_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Meta description'),
        ),
    ]
