# Generated by Django 3.2.9 on 2022-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20220131_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobject',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
