# Generated by Django 3.2.9 on 2022-02-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_rentobject_street'),
        ('objects', '0009_alter_rentobject_attachment'),
    ]

    operations = [
    ]
