# Generated by Django 3.2.9 on 2022-02-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20220209_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='regular_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='seo_text',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='regular_url',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='seo_text',
        ),
    ]
