# Generated by Django 3.2.9 on 2022-02-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20220209_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
