# Generated by Django 3.2.9 on 2022-02-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20220214_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='text_ru',
        ),
    ]
