# Generated by Django 3.2.9 on 2022-02-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20220214_0516'),
        ('objects', '0014_auto_20220214_1736'),
    ]

    operations = [
    ]
