# Generated by Django 3.2.9 on 2022-02-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_merge_0013_auto_20220214_0516_0014_auto_20220214_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobjectreserv',
            name='adults',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adults'),
        ),
        migrations.AlterField(
            model_name='rentobjectreserv',
            name='animals',
            field=models.BooleanField(default=False, verbose_name='With pets'),
        ),
        migrations.AlterField(
            model_name='rentobjectreserv',
            name='kids',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kids'),
        ),
        migrations.AlterField(
            model_name='rentobjectreserv',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
