# Generated by Django 3.2.9 on 2022-02-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_auto_20220215_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentobjectimage',
            options={'ordering': ['order'], 'verbose_name': 'Image'},
        ),
        migrations.AddField(
            model_name='rentobjectimage',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Display order'),
        ),
    ]
