# Generated by Django 3.2.9 on 2022-02-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20220215_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailandfeature',
            name='property',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
