# Generated by Django 3.2.9 on 2022-03-03 03:48

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_alter_detailandfeature_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobject',
            name='hidden_details',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rentobject',
            name='text',
        ),
        migrations.CreateModel(
            name='RentObjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('hidden_details', models.CharField(blank=True, max_length=255, verbose_name='Hidden details')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='objects.rentobject')),
            ],
            options={
                'verbose_name': 'rent object Translation',
                'db_table': 'objects_rentobject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
