# Generated by Django 3.2.9 on 2022-03-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_auto_20220303_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobjecttranslation',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='rentobjecttranslation',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='rentobjecttranslation',
            name='seo_title',
        ),
    ]
