# Generated by Django 3.2.9 on 2022-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_auto_20220303_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobjecttranslation',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
