# Generated by Django 3.2.9 on 2022-03-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0025_auto_20220303_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobject',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='objects.Amenity'),
        ),
        migrations.AlterField(
            model_name='rentobject',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
