# Generated by Django 3.2.9 on 2021-12-23 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=20, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/feedbacks/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Meta description')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка для списка')),
                ('image_detail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка для деталки')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('viewed', models.PositiveIntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
