# Generated by Django 3.2.9 on 2021-12-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Picture for the list'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_detail',
            field=models.ImageField(null=True, upload_to='', verbose_name='Picture for detail'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of views'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/feedbacks/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
