# Generated by Django 3.2.9 on 2022-03-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20220216_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_keywords_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_title_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_ru',
        ),
    ]
