# Generated by Django 3.2.9 on 2022-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20220302_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='blogtranslation',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short description'),
        ),
    ]
