# Generated by Django 3.2.9 on 2022-02-09 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo', '0001_initial'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageExt',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('seo_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords')),
                ('seo_description', models.TextField(blank=True, max_length=255, verbose_name='Meta description')),
                ('seo_text', models.TextField(blank=True, null=True)),
                ('regular_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.regularurl')),
            ],
            options={
                'verbose_name': 'Flat Page Custom',
                'verbose_name_plural': 'Flat pages',
            },
            bases=('flatpages.flatpage', models.Model),
        ),
    ]
