# Generated by Django 3.2.9 on 2022-02-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, verbose_name='Meta title')),
                ('seo_keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords')),
                ('seo_description', models.TextField(blank=True, max_length=255, verbose_name='Meta description')),
                ('seo_text', models.TextField(blank=True, null=True)),
                ('regular_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.regularurl')),
            ],
            options={
                'verbose_name': 'Seo',
                'verbose_name_plural': 'Seo',
            },
        ),
    ]
