# Generated by Django 3.2.9 on 2022-02-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_auto_20220217_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainseo',
            name='url',
            field=models.CharField(blank=True, max_length=2100, null=True),
        ),
    ]
