# Generated by Django 3.2.9 on 2022-03-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_mainseo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_description_en',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_description_ru',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_keywords_en',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_keywords_ru',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_text_en',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_text_ru',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_title_en',
        ),
        migrations.RemoveField(
            model_name='mainseo',
            name='seo_title_ru',
        ),
    ]
