# Generated by Django 3.2.9 on 2021-12-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Currency Code (ISO 4217)', max_length=3, verbose_name='Currency')),
                ('symbol', models.CharField(help_text='Currency sign, to be used when printing amounts.', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
